# site settings
title: Alej's Personal Site
author: Alejandra Castaneda
email: agca2020@mymail.pomona.edu
description: Bookmark this to keep an eye on my project updates!

# Build Settings
theme: jekyll-theme-minimal
